### ISSUE TITLE
Custom Searchers Configuration

### ISSUE THREAD

**Issue by samirlalvani** [NCSU-Libraries/quick_search#16]
The last step in the **Configuring Searchers** method (https://github.com/NCSU-Libraries/quick_search/blob/master/docs/configuration.md) specifies editing the _app/views/quick_search/search/index.html.erb_ file. But this path does not exist on a clean build. I see it in the GitHub repo so is there something in the local configuration that I'm missing? Thanks!

**Comment by kbeswick** [comment]
Hi Samir,

This file defines the search results page, and is meant to be overridden/customized. You can either do this within a theme gem (if you'd like to create a custom theme), or you can override it in the base application you created (where the quick_search-core gem was included).

To override, you can just create a file within the application with the same name/path mentioned above. I'd recommend using this version as a base, and then make changes to it: https://github.com/NCSU-Libraries/quick_search-generic_theme/blob/master/app/views/quick_search_generic_theme/quick_search/search/index.html.erb

Here is the order of precedence in which QuickSearch looks for overridden views:
1. Wrapper application where you included the quick_search-core gem (it looks here first, then falls back if it can't find the view)
2. Theme gem that is included in the application (quick_search-generic_theme by default)
3. quick_search-core
4. Any other included gem

The theming documentation needs to be fleshed out more. Since the open source version is still in its early stages, we haven't really come up with definitive best practices to follow. We've recently migrated a second application to use the QuickSearch platform, so we have some new ideas and hopefully will get this documentation updated soon.

All this to say, if you have any issues, ideas, feedback, we'd love to hear it! Please don't hesitate to reach out in the future!

**Comment by samirlalvani** [comment]
Thanks for the details, Kevin! Let me tweak things as per your suggestions and close the issue within the next day or two.

**Comment by samirlalvani** [comment]
Hi Kevin,

This suggestion worked perfectly. What really helped was the order of precedence and digging into the bundler versions of gems in addition to the main project directory. Including it into the documentation would be really helpful for people new to quick_search.

Thanks!
